#---standard pioneer footprint---
#---(in meters)---
# robot_radius: 0.3
# footprint: [[-0.1,-0.10],[0.5,-0.10],[0.5,0.10],[-0.1,0.10]] # true: 0.33
footprint: [[-0.28,-0.33],[1.12,-0.33],[1.12,0.33],[-0.28,0.33]]

transform_tolerance: 0.2
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 25.0 # the range limit of 2d lasers
 raytrace_range: 25.0
 inflation_radius: 0.1
 track_unknown_space: true
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {
  data_type: LaserScan, 
  topic: merged_scan,
  clearing: true, 
  observation_persistence: 1.0,
  inf_is_valid: true
  }
#  point_cloud2_sensor: {data_type: PointCloud2, topic: rslidar_points, marking: true, clearing: true, max_obstacle_height: 1.8, min_obstacle_height: 0.5}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.1  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"
