DWAPlannerROS:

# Robot Configuration Parameters - stdr robot

  acc_lim_x: 2.0  # maximum is theoretically 2.0
  acc_lim_y: 0.0  # diff drive robot
  acc_lim_th: 2.0

  max_trans_vel: 0.4 #choose slightly less than the base's capability
  min_trans_vel: 0.0 #this is the min trans velocity when there is negligible rotational velocity 

  max_vel_x: 0.4
  min_vel_x: -0.1 

  max_rot_vel: 0.6  #choose slightly less than the base's capability
  min_rot_vel: 0.0  #this is the min angular velocity when there is negligible translational velocity
 

# Goal Tolerance Parameters

  yaw_goal_tolerance: 0.3  # 0.1 rad = 5.7 degree
  xy_goal_tolerance: 0.4
  latch_xy_goal_tolerance: false


# Oscillation Prevention Parameters

  oscillation_reset_dist: 0.05  # default 0.05
 

# Global Plan Parameters

  prune_plan: false
